name: build and push docker image

on:
  push:
    branches: ['master']
    
jobs:
  push_to_docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sarangp007
          password: timers123
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: gitpos:latest
      -
        name: Inspect
        run: |
          docker image inspect sarangp007/gitops:latest
        
